### PR TITLE
Update README w/ note about GH plans supporting attestations

### PR DESCRIPTION
**Pull request by bdehamer**
Updates the readme with a note outlining which GH plans support artifact attestations.

image

### CODE REVIEW

**Review by codysoyland — APPROVED** [review]

**Comment by ETEnterprises1** [comment]
Needshelp@bdehamer

**Comment by ETEnterprises1** [comment]
I was a cloud plan just they locked me out of "master333-ui-web"

**Comment by ETEnterprises1** [comment]
That's my company account

**Comment by ETEnterprises1** [comment]
> Updates the readme with a note outlining which GH plans support artifact attestations.
> 
> image
>

**Comment by ETEnterprises1** [comment]
-git request -pull > > Updates the readme with a note outlining which GH plans support artifact attestations.
> > 
> > image
> > 
> 
>

**Comment by ETEnterprises1** [comment]
`> -git request -pull > > Updates the readme with a note outlining which GH plans support artifact attestations.
> > > 
> > > image
> > > 
> > 
> > 
> 
> 

`

**Pull request merged**
